version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

volumes:
  mariadb_data:
    driver: local
