apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: elasticsearch
    name: elasticsearch
  spec:
    ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
    selector:
      io.kompose.service: elasticsearch
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: elasticsearch
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: elasticsearch
      spec:
        containers:
        - image: bitnami/elasticsearch:latest
          name: elasticsearch
          ports:
          - containerPort: 9200
          - containerPort: 9300
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/elasticsearch
            name: elasticsearch-elasticsearch-data
        restartPolicy: Always
        volumes:
        - name: elasticsearch-elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-elasticsearch-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: elasticsearch-elasticsearch-data
    name: elasticsearch-elasticsearch-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

