apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: wildfly
    name: wildfly
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9990"
      port: 9990
      targetPort: 9990
    selector:
      io.kompose.service: wildfly
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: wildfly
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: wildfly
      spec:
        containers:
        - env:
          - name: WILDFLY_PASSWORD
            value: password
          image: bitnami/wildfly:latest
          name: wildfly
          ports:
          - containerPort: 8080
          - containerPort: 9990
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/wildfly
            name: wildfly-wildfly-data
        restartPolicy: Always
        volumes:
        - name: wildfly-wildfly-data
          persistentVolumeClaim:
            claimName: wildfly-wildfly-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: wildfly-wildfly-data
    name: wildfly-wildfly-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

