version: '2'

services:
  mongodb:
    image: bitnami/mongodb:latest

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/express:latest
    command: npm start
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/app
