version: '2'

services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_DATABASE=my_app_development

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/express:latest
    environment:
      - DATABASE_URL=mysql://root@mariadb/my_app_development
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app
