version: '2'

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=my_app

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/express:latest
    command: npm start
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres@postgresql/my_app
    depends_on:
      - postgresql
    ports:
      - 3000:3000
    volumes:
      - .:/app
