version: '2'

services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_DATABASE=myapp

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/express:latest
    command: npm start
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mysql://root@mariadb/myapp
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app
