version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    build: .
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - 'discourse_data:/bitnami/discourse'
  sidekiq:
    build: .
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse-sidekiq'
    command: 'nami start --foreground discourse-sidekiq'
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
