version: '2'
services:
  mysql:
    image: 'bitnami/mysql:8.0'
    volumes:
      - 'mysql_data:/bitnami'
    environment:
      - MYSQL_USER=bn_wordpress
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_ROOT_PASSWORD=bitnami123
      - MYSQL_PASSWORD=bitnami123
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mysql
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami123
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
