## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-redis-exporter
  name: test-redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-redis-exporter
  template:
    metadata:
      labels:
        app: test-redis-exporter
    spec:
      containers:
      - image: bitnami/redis-exporter
        name: redis-exporter
