apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: odoo
    name: odoo
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 8069
    - name: "443"
      port: 443
      targetPort: 8071
    selector:
      io.kompose.service: odoo
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: postgresql
    name: postgresql
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: postgresql
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: odoo
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: odoo
      spec:
        containers:
        - image: bitnami/odoo:latest
          name: odoo
          ports:
          - containerPort: 8069
          - containerPort: 8071
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/odoo
            name: odoo-odoo-data
        restartPolicy: Always
        volumes:
        - name: odoo-odoo-data
          persistentVolumeClaim:
            claimName: odoo-odoo-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: odoo-odoo-data
    name: odoo-odoo-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: postgresql
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: postgresql
      spec:
        containers:
        - image: bitnami/postgresql:latest
          name: postgresql
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/postgresql
            name: odoo-postgresql-data
        restartPolicy: Always
        volumes:
        - name: odoo-postgresql-data
          persistentVolumeClaim:
            claimName: odoo-postgresql-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: odoo-postgresql-data
    name: odoo-postgresql-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

