version: '2'
services:
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch'
  kibana:
    build: .
    ports:
      - '5601:5601'
    volumes:
      - 'kibana_data:/bitnami/kibana'
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
