apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cassandra
    name: cassandra
  spec:
    ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    - name: "7001"
      port: 7001
      targetPort: 7001
    - name: "9042"
      port: 9042
      targetPort: 9042
    - name: "9160"
      port: 9160
      targetPort: 9160
    selector:
      io.kompose.service: cassandra
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: cassandra
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cassandra
      spec:
        containers:
        - image: bitnami/cassandra:latest
          name: cassandra
          ports:
          - containerPort: 7000
          - containerPort: 7001
          - containerPort: 9042
          - containerPort: 9160
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/cassandra
            name: cassandra-cassandra-data
        restartPolicy: Always
        volumes:
        - name: cassandra-cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-cassandra-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cassandra-cassandra-data
    name: cassandra-cassandra-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

