apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: kafka
    name: kafka
  spec:
    ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    selector:
      io.kompose.service: kafka
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: zookeeper
    name: zookeeper
  spec:
    ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    selector:
      io.kompose.service: zookeeper
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: kafka
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: kafka
      spec:
        containers:
        - env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          image: bitnami/kafka:latest
          name: kafka
          ports:
          - containerPort: 9092
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/kafka
            name: bitnamidockerkafka-kafka-data
        restartPolicy: Always
        volumes:
        - name: bitnamidockerkafka-kafka-data
          persistentVolumeClaim:
            claimName: bitnamidockerkafka-kafka-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: bitnamidockerkafka-kafka-data
    name: bitnamidockerkafka-kafka-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: zookeeper
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: zookeeper
      spec:
        containers:
        - image: bitnami/zookeeper:latest
          name: zookeeper
          ports:
          - containerPort: 2181
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/zookeeper
            name: bitnamidockerkafka-zookeeper-data
        restartPolicy: Always
        volumes:
        - name: bitnamidockerkafka-zookeeper-data
          persistentVolumeClaim:
            claimName: bitnamidockerkafka-zookeeper-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: bitnamidockerkafka-zookeeper-data
    name: bitnamidockerkafka-zookeeper-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

