version: '2'

services:
  apache:
    # Force docker-compose to use a comprehensive name for the image
    image: bitnami_apache:2.4-rhel-7
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'apache_data:/bitnami'
volumes:
  apache_data:
    driver: local
