name: '[Support] Organizing cards based on comments'
on:
  issue_comment:
    types:
      - created
permissions:
  repository-projects: write
  issues: write
  pull-requests: write

jobs:
  comments_handler:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
      - name: Move into From Bitnami
        uses: peter-evans/create-or-update-project-card@v2
        if: ${{ github.actor == 'bitnami-bot' }}
        with:
          project-name: Support
          column-name: From Bitnami
          # Required to trigger moving-cards.yml workflow (clean labels and assign people to work on it)
          # NOTE: we will need to change it when the new column for failed automated PRs is created
          token: "${{ secrets.BITNAMI_BOT_TOKEN }}"
      - name: Move into Pending
        uses: peter-evans/create-or-update-project-card@v2
        if: ${{ github.actor != 'bitnami-bot' && (!contains(github.event.issue.labels.*.name, 'bitnami')) && contains(fromJson(env.BITNAMI_TEAM), github.actor) }}
        with:
          project-name: Support
          column-name: Pending
      - name: Move into In Progress
        uses: peter-evans/create-or-update-project-card@v2
        if: ${{ github.actor != 'bitnami-bot' && contains(github.event.issue.labels.*.name, 'in-progress') && (!contains(fromJson(env.BITNAMI_TEAM), github.actor)) }}
        with:
          project-name: Support
          column-name: In progress
      - name: Move into Triage
        uses: peter-evans/create-or-update-project-card@v2
        if: ${{ github.actor != 'bitnami-bot' && ((contains(github.event.issue.labels.*.name, 'triage')) || (contains(github.event.issue.labels.*.name, 'solved'))) && (!contains(fromJson(env.BITNAMI_TEAM), github.actor)) }}
        with:
          project-name: Support
          column-name: Triage
          # Needs reasignation of the task
          token: "${{ secrets.BITNAMI_BOT_TOKEN }}"