# This workflow is built to manage the triage support by using GH issues.
name: '[Support] Cards movements'
on:
  project_card:
    types:
      - moved

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  get-issue:
    runs-on: ubuntu-latest
    name: Get issue info
    outputs:
      assignees: ${{ steps.get-issue-step.outputs.assignees }}
      creator: ${{ steps.get-issue-step.outputs.creator }}
    steps:
      - name: Get issue info
        id: get-issue-step
        run: |
          issue_info=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G ${{ github.event.project_card.content_url }})
          assignees="$(echo $issue_info | jq -r '.assignees')"
          creator="$(echo $issue_info | jq -r '.user.login')"
          echo "::set-output name=assignees::${assignees}"
          echo "::set-output name=creator::${creator}"
  label-card:
    runs-on: ubuntu-latest
    needs:
      - get-issue
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
      # Now handling the needed labeling
      - name: Triage labeling
        # Only if moved into triage
        if: ${{ github.event.project_card.column_id == env.TRIAGE_COLUMN_ID  }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "triage"
          remove-labels: "on-hold, in-progress, solved"
      - name: From Bitnami labeling
        # NOTE: This step has to be modified when a new column for automated PR is added
        if: |
          github.event.project_card.column_id == env.BITNAMI_COLUMN_ID &&
          (needs.get-issue.outputs.creator == 'bitnami-bot')
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "review-required"
          remove-labels: "auto-merge"
      - name: On hold labeling
        # Only if moved into on hold
        if: ${{ github.event.project_card.column_id == env.ON_HOLD_COLUMN_ID  }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "on-hold"
          remove-labels: "triage, in-progress, solved"
      - name: In progress labeling
        # Only if moved into In progress
        if: ${{ github.event.project_card.column_id == env.IN_PROGRESS_COLUMN_ID  }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "in-progress"
          remove-labels: "on-hold, triage, solved"
      - name: Solved labeling
        # Only if moved into Solved and the issue creator is not bitnami-bot
        if: |
          github.event.project_card.column_id == env.SOLVED_COLUMN_ID &&
          (needs.get-issue.outputs.creator != 'bitnami-bot')
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "solved"
          remove-labels: "in-progress, on-hold, triage"
  assign-assignee-if-needed:
    runs-on: ubuntu-latest
    needs:
      - get-issue
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
      - name: Assign to a person to work on it
        # Only if nobody is assigned or moved into In progress FROM Triage
        if: |
          needs.get-issue.outputs.assignees == '[]' ||
          github.event.project_card.column_id == env.IN_PROGRESS_COLUMN_ID && github.event.changes != null && github.event.changes.column_id &&
          github.event.changes.column_id.from == env.TRIAGE_COLUMN_ID
        uses: pozil/auto-assign-issue@v1.9.0
        with:
          numOfAssignee: 1
          removePreviousAssignees: true
          teams: ${{ env.SUPPORT_TEAM_NAME }}
          repo-token: "${{ secrets.BITNAMI_BOT_TOKEN }}"
        # NOTE: New assignment rule has to be added when the new column for automated PR is added