name: Sync containers repositories

on:
  schedule:
    # Every day at 1 AM
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Sync deprecations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bitnami/containers
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BITNAMI_BOT_SECRET }}
          fetch-depth: 0
      - name: Sync Containers
        run: ./scripts/sync-deprecations.sh